[LegalNotice]
Accepted=true

[BitTorrent]
Session\AddExtensionToIncompleteFiles=true
Session\AsyncIOThreadsCount=16
Session\DHTEnabled=true
Session\DefaultSavePath=/downloads
Session\DiskCacheSize=1024
Session\DiskIOType=1
Session\ExcludedFileNames=
Session\GlobalMaxInactiveSeedingMinutes=-1
Session\GlobalMaxRatio=-1
Session\GlobalMaxSeedingMinutes=-1
Session\LSDEnabled=true
Session\MaxActiveCheckingTorrents=5
Session\MaxActiveDownloads=20
Session\MaxActiveTorrents=30
Session\MaxActiveUploads=10
Session\MaxConnections=3000
Session\MaxConnectionsPerTorrent=800
Session\MaxUploads=200
Session\MaxUploadsPerTorrent=80
Session\PeXEnabled=true
Session\Port=6881
Session\QueueingSystemEnabled=true
Session\SSL\Port=6882
Session\TempPath=/downloads/.incomplete
Session\TempPathEnabled=true
Session\uTPRateLimited=false

[Network]
PortForwardingEnabled=true

[Preferences]
Advanced\AnnounceToAllTrackers=true
Advanced\AnnounceToAllTiers=true
Advanced\osCache=true
Connection\PortRangeMin=6881
Connection\ResolvePeerCountries=false
Connection\UPnP=true
Downloads\SavePath=/downloads
WebUI\Address=*
WebUI\HostHeaderValidation=false
WebUI\LocalHostAuth=false
WebUI\Password_PBKDF2="@ByteArray(ARQ77eY1NUZaQsuDHbIMCA==:0WMRkYTUWVT9wVvdDtHAjU9b3b7uB8NR1Gur2hmQCvCDpm39Q+PsJRJPaCU51dEiz+dTzh8qbPsL8WkFljQYFQ==)"
WebUI\Port=8080
WebUI\ServerDomains=*
WebUI\Username=admin
