<?php

return [
    'cast_url_ttl_seconds' => env('MEDIA_CAST_URL_TTL_SECONDS', 21600),

    'adaptive' => [
        'enabled' => env('MEDIA_ADAPTIVE_STREAMS_ENABLED', true),
        'url_ttl_seconds' => env('MEDIA_ADAPTIVE_STREAM_URL_TTL_SECONDS', 21600),
        'ffmpeg_binary' => env('MEDIA_ADAPTIVE_FFMPEG_BINARY', 'ffmpeg'),
        'ffmpeg_preset' => env('MEDIA_ADAPTIVE_FFMPEG_PRESET', 'veryfast'),
        'ffmpeg_timeout_seconds' => env('MEDIA_ADAPTIVE_FFMPEG_TIMEOUT_SECONDS', 3600),
        'hls_time_seconds' => env('MEDIA_ADAPTIVE_HLS_TIME_SECONDS', 6),
        'variants' => [
            [
                'name' => '1080p',
                'height' => 1080,
                'width' => 1920,
                'video_bitrate' => '5000k',
                'audio_bitrate' => '160k',
                'bandwidth' => 5600000,
            ],
            [
                'name' => '720p',
                'height' => 720,
                'width' => 1280,
                'video_bitrate' => '2800k',
                'audio_bitrate' => '128k',
                'bandwidth' => 3200000,
            ],
            [
                'name' => '480p',
                'height' => 480,
                'width' => 854,
                'video_bitrate' => '1200k',
                'audio_bitrate' => '96k',
                'bandwidth' => 1500000,
            ],
            [
                'name' => '360p',
                'height' => 360,
                'width' => 640,
                'video_bitrate' => '700k',
                'audio_bitrate' => '64k',
                'bandwidth' => 850000,
            ],
            [
                'name' => '240p',
                'height' => 240,
                'width' => 426,
                'video_bitrate' => '350k',
                'audio_bitrate' => '48k',
                'bandwidth' => 450000,
            ],
        ],
    ],

    'yt_dlp' => [
        'binary' => env('YTDLP_BINARY', 'yt-dlp'),
        'inspect_timeout' => env('YTDLP_INSPECT_TIMEOUT', 60),
        'download_timeout' => env('YTDLP_DOWNLOAD_TIMEOUT', 3600),
        'target_bandwidth_mbps' => env('DOWNLOAD_TARGET_BANDWIDTH_MBPS', 10000),
        'adaptive_segments' => env('YTDLP_ADAPTIVE_SEGMENTS', true),
        'concurrent_fragments' => env('YTDLP_CONCURRENT_FRAGMENTS', 256),
        'max_concurrent_fragments' => env('YTDLP_MAX_CONCURRENT_FRAGMENTS', 1024),
        'http_chunk_size' => env('YTDLP_HTTP_CHUNK_SIZE', '64M'),
        'external_downloader' => env('YTDLP_EXTERNAL_DOWNLOADER', 'aria2c'),
        'external_downloader_args' => env('YTDLP_EXTERNAL_DOWNLOADER_ARGS'),
        'segment_connections' => env('YTDLP_SEGMENT_CONNECTIONS', 256),
        'max_segment_connections' => env('YTDLP_MAX_SEGMENT_CONNECTIONS', 1024),
        'segment_split' => env('YTDLP_SEGMENT_SPLIT', 256),
        'max_segment_split' => env('YTDLP_MAX_SEGMENT_SPLIT', 1024),
        'segment_min_split_size' => env('YTDLP_SEGMENT_MIN_SPLIT_SIZE', '1M'),
        'segment_piece_length' => env('YTDLP_SEGMENT_PIECE_LENGTH', '1M'),
        'segment_disk_cache' => env('YTDLP_SEGMENT_DISK_CACHE', '1024M'),
        'retries' => env('YTDLP_RETRIES', 10),
        'fragment_retries' => env('YTDLP_FRAGMENT_RETRIES', 10),
        'socket_timeout' => env('YTDLP_SOCKET_TIMEOUT', 30),
        'cookies' => env('YTDLP_COOKIES'),
        'cookies_from_browser' => env('YTDLP_COOKIES_FROM_BROWSER'),
        'youtube_player_clients' => env('YTDLP_YOUTUBE_PLAYER_CLIENTS', 'mweb,web_safari,android_vr'),
        'pot_provider_url' => env('YTDLP_POT_PROVIDER_URL'),
        'pot_disable_innertube' => env('YTDLP_POT_DISABLE_INNERTUBE', true),
    ],
];
