<?php

return [
    'yt_dlp' => [
        'binary' => env('YTDLP_BINARY', 'yt-dlp'),
        'inspect_timeout' => env('YTDLP_INSPECT_TIMEOUT', 60),
        'download_timeout' => env('YTDLP_DOWNLOAD_TIMEOUT', 3600),
        'adaptive_segments' => env('YTDLP_ADAPTIVE_SEGMENTS', true),
        'concurrent_fragments' => env('YTDLP_CONCURRENT_FRAGMENTS', 64),
        'max_concurrent_fragments' => env('YTDLP_MAX_CONCURRENT_FRAGMENTS', 192),
        'http_chunk_size' => env('YTDLP_HTTP_CHUNK_SIZE', '32M'),
        'external_downloader' => env('YTDLP_EXTERNAL_DOWNLOADER', 'aria2c'),
        'external_downloader_args' => env('YTDLP_EXTERNAL_DOWNLOADER_ARGS'),
        'segment_connections' => env('YTDLP_SEGMENT_CONNECTIONS', 64),
        'max_segment_connections' => env('YTDLP_MAX_SEGMENT_CONNECTIONS', 192),
        'segment_split' => env('YTDLP_SEGMENT_SPLIT', 64),
        'max_segment_split' => env('YTDLP_MAX_SEGMENT_SPLIT', 192),
        'segment_min_split_size' => env('YTDLP_SEGMENT_MIN_SPLIT_SIZE', '1M'),
        'segment_piece_length' => env('YTDLP_SEGMENT_PIECE_LENGTH', '1M'),
        'segment_disk_cache' => env('YTDLP_SEGMENT_DISK_CACHE', '256M'),
        'retries' => env('YTDLP_RETRIES', 10),
        'fragment_retries' => env('YTDLP_FRAGMENT_RETRIES', 10),
        'socket_timeout' => env('YTDLP_SOCKET_TIMEOUT', 30),
        'cookies' => env('YTDLP_COOKIES'),
        'cookies_from_browser' => env('YTDLP_COOKIES_FROM_BROWSER'),
        'youtube_player_clients' => env('YTDLP_YOUTUBE_PLAYER_CLIENTS', 'mweb,web_safari,android_vr'),
        'pot_provider_url' => env('YTDLP_POT_PROVIDER_URL'),
        'pot_disable_innertube' => env('YTDLP_POT_DISABLE_INNERTUBE', true),
    ],
];
