<?php

return [
    'default_user_quota_bytes' => (int) env('TORRENTS_DEFAULT_USER_QUOTA_BYTES', 734003200),
    'global_active_limit' => (int) env('TORRENTS_GLOBAL_ACTIVE_LIMIT', 5),

    'qbittorrent' => [
        'base_url' => env('QBITTORRENT_BASE_URL', 'http://qbittorrent:8080'),
        'username' => env('QBITTORRENT_USERNAME'),
        'password' => env('QBITTORRENT_PASSWORD'),
        'timeout' => (int) env('QBITTORRENT_TIMEOUT', 10),
        'metadata_poll_attempts' => (int) env('QBITTORRENT_METADATA_POLL_ATTEMPTS', 30),
        'metadata_poll_interval_ms' => (int) env('QBITTORRENT_METADATA_POLL_INTERVAL_MS', 1000),
        'keep_after_import' => env('QBITTORRENT_KEEP_AFTER_IMPORT', true),
        'performance_preferences' => [
            'listen_port' => (int) env('QBITTORRENT_TORRENTING_PORT', 6881),
            'random_port' => false,
            'dl_limit' => (int) env('QBITTORRENT_DOWNLOAD_LIMIT_KIB', -1),
            'up_limit' => (int) env('QBITTORRENT_UPLOAD_LIMIT_KIB', -1),
            'alt_dl_limit' => (int) env('QBITTORRENT_ALT_DOWNLOAD_LIMIT_KIB', -1),
            'alt_up_limit' => (int) env('QBITTORRENT_ALT_UPLOAD_LIMIT_KIB', -1),
            'scheduler_enabled' => false,
            'queueing_enabled' => false,
            'max_active_downloads' => (int) env('QBITTORRENT_MAX_ACTIVE_DOWNLOADS', 100),
            'max_active_torrents' => (int) env('QBITTORRENT_MAX_ACTIVE_TORRENTS', 150),
            'max_active_uploads' => (int) env('QBITTORRENT_MAX_ACTIVE_UPLOADS', 150),
            'connection_speed' => (int) env('QBITTORRENT_CONNECTION_SPEED', 10000),
            'async_io_threads' => (int) env('QBITTORRENT_ASYNC_IO_THREADS', 128),
            'disk_cache' => (int) env('QBITTORRENT_DISK_CACHE_MB', 32768),
            'max_connec' => (int) env('QBITTORRENT_MAX_CONNECTIONS', 64000),
            'max_connec_per_torrent' => (int) env('QBITTORRENT_MAX_CONNECTIONS_PER_TORRENT', 16000),
            'max_uploads' => (int) env('QBITTORRENT_MAX_UPLOADS', 8000),
            'max_uploads_per_torrent' => (int) env('QBITTORRENT_MAX_UPLOADS_PER_TORRENT', 2000),
            'max_concurrent_http_announces' => (int) env('QBITTORRENT_MAX_CONCURRENT_HTTP_ANNOUNCES', 1000),
            'max_ratio' => (int) env('QBITTORRENT_MAX_RATIO', -1),
            'max_seeding_time' => (int) env('QBITTORRENT_MAX_SEEDING_TIME_MINUTES', -1),
            'max_inactive_seeding_time' => (int) env('QBITTORRENT_MAX_INACTIVE_SEEDING_TIME_MINUTES', -1),
            'upnp' => env('QBITTORRENT_UPNP', true),
            'dht' => true,
            'pex' => true,
            'lsd' => true,
            'add_trackers_enabled' => trim((string) env('QBITTORRENT_EXTRA_TRACKERS', '')) !== '',
            'add_trackers' => trim(str_replace(',', "\n", (string) env('QBITTORRENT_EXTRA_TRACKERS', ''))),
            'announce_to_all_trackers' => true,
            'announce_to_all_tiers' => true,
            'limit_utp_rate' => false,
            'limit_tcp_overhead' => false,
            'limit_lan_peers' => false,
            'enable_multi_connections_from_same_ip' => env('QBITTORRENT_MULTI_CONNECTIONS_FROM_SAME_IP', true),
            'enable_os_cache' => true,
            'socket_receive_buffer_size' => (int) env('QBITTORRENT_SOCKET_RECEIVE_BUFFER_SIZE', 67108864),
            'socket_send_buffer_size' => (int) env('QBITTORRENT_SOCKET_SEND_BUFFER_SIZE', 67108864),
            'send_buffer_watermark' => (int) env('QBITTORRENT_SEND_BUFFER_WATERMARK', 16384),
            'send_buffer_low_watermark' => (int) env('QBITTORRENT_SEND_BUFFER_LOW_WATERMARK', 1024),
            'send_buffer_watermark_factor' => (int) env('QBITTORRENT_SEND_BUFFER_WATERMARK_FACTOR', 500),
        ],
    ],
];
