apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloora
resources:
  - namespace.yaml
  - configmap.yaml
  - storage.yaml
  - postgres.yaml
  - redis.yaml
  - rustfs.yaml
  - qbittorrent.yaml
  - migrate-job.yaml
  - app.yaml
  - queue.yaml
  - scheduler.yaml
  - ingress.yaml
